blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls')),
    path('', views.index, name='index'),
]

demo/urls.py
from django.urls import path, include
from . import views

app_name = "demo"

urlpatterns = [
    path('users', views.index, name='index'),
    path('users/create', views.create, name='create'),
    path('users/edit/<int:id>', views.edit, name='edit'),
    path('users/delete/<int:id>', views.delete, name='delete'),
]

demo/models.py
from django.db import models
import datetime


class Customers(models.Model):
    FirstName = models.CharField(max_length=50)
    LastName = models.CharField(max_length=50)
    FullName = models.CharField(max_length=100, blank=True)
    Password = models.CharField(max_length=50)
    Birthday = models.DateField()
    Hobbies = models.CharField(max_length=250)
    Description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.FullName = self.FirstName + ' ' + self.LastName
        if self.Birthday == '':
            self.Birthday = datetime.datetime.now()
        super().save(*args, **kwargs)


class Groups(models.Model):
    choice_permissions = (
        (0, 'N/A'),
        (1, 'ADD'),
        (2, 'EDIT'),
        (3, 'DELETE')
    )
    Name = models.CharField(max_length=100)
    Permissions = models.IntegerField(choices=choice_permissions, default=0)
    Description = models.CharField(max_length=250)


class Roles(models.Model):
    choice_permissions = (
        (0, 'N/A'),
        (1, 'ADMIN'),
        (2, 'PUBLISHER'),
        (3, 'APPROVER'),
        (4, 'MODERATOR'),
        (5, 'EDITOR'),
        (6, 'CREATOR'),
    )
    Name = models.CharField(max_length=100)
    Permissions = models.IntegerField(choices=choice_permissions, default=0)
    Description = models.CharField(max_length=250)


class Customer_Group(models.Model):
    Customer_ID = models.ForeignKey(Customers, on_delete=models.CASCADE)
    Group_ID = models.ForeignKey(Groups, on_delete=models.CASCADE)


class Customer_Role(models.Model):
    Customer_ID = models.ForeignKey(Customers, on_delete=models.CASCADE)
    Role_ID = models.ForeignKey(Roles, on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

demo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime

from .models import Customers, Groups, Roles

from pdb import set_trace as byebug


def index(request):
    rs = Customers.objects.all()
    context = {
        'data': rs,
    }
    return render(request, 'users/index.html', context)


def create(request):
    if request.method == "POST":
        rs = Customers(FirstName=request.POST['FirstName'],
                       LastName=request.POST['LastName'],
                       Password=request.POST['Password'],
                       Birthday=request.POST['Birthday'],
                       Hobbies=request.POST['Hobbies'],
                       Description=request.POST['Description'])

        rs.save()

        return HttpResponseRedirect(reverse('demo:edit', args=(rs.id,)))
    else:
        return render(request, 'users/form.html')


def edit(request, id):
    if request.method == "POST":
        rs = Customers.objects.get(pk=id)
        rs.FirstName = request.POST['FirstName']
        rs.LastName = request.POST['LastName']
        rs.Password = request.POST['Password']
        rs.Birthday = request.POST['Birthday']
        rs.Hobbies = request.POST['Hobbies']
        rs.Description = request.POST['Description']

        rs.save()

        return HttpResponseRedirect(reverse('demo:edit', args=(rs.id,)))
    else:
        rs = Customers.objects.get(pk=id)
        rs.Birthday = rs.Birthday.strftime("%Y-%m-%d")
        context = {
            'data': rs
        }
        return render(request, 'users/form.html', context)


def delete(request, id):
    rs = Customers.objects.get(pk=id)
    rs.delete()
    return HttpResponseRedirect(reverse('demo:index'))

demo/templates/users/form.html
{% extends "base.html" %} {% block content %}
<ul class="clearfix" id="nav-info">
    <li>
        <a href="#">
            <i class="icon-home"></i>
        </a>
    </li>
    <li class="active">
        <a href="#">Quản lý Users</a>
    </li>
</ul>

<div class="clearfix">

    <h4>
        {% if data %} Thông tin User {% else %} Thêm mới User {% endif %}
    </h4>

    <form method="post" action="" id="Form1" class="form-horizontal form-box form-archive" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-box-content">

            {% if data.FullName %}

            <div class="control-group">
                <label for="FullName" class="control-label">FullName</label>
                <div class="controls">
                    <strong>{{ data.FullName }}</strong>
                </div>
            </div>

            {% endif %}

            <div class="control-group">
                <label for="FirstName" class="control-label">FirstName</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="FirstName" name="FirstName" value="{{ data.FirstName }}">
                </div>
            </div>

            <div class="control-group">
                <label for="LastName" class="control-label">LastName</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="LastName" name="LastName" value="{{ data.LastName }}">
                </div>
            </div>

            <div class="control-group">
                <label for="Password" class="control-label">Password</label>
                <div class="controls">
                    <input type="password" class="input-xlarge" id="Password" name="Password" value="{{ data.Password }}">
                </div>
            </div>

            <div class="control-group">
                <label for="Birthday" class="control-label">Birthday</label>
                <div class="controls">
                    <input type="date" class="input-xlarge" id="Birthday" name="Birthday" value="{{ data.Birthday }}">
                </div>
            </div>

            <div class="control-group">
                <label for="Hobbies" class="control-label">Hobbies</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="Hobbies" name="Hobbies" value="{{ data.Hobbies }}">
                </div>
            </div>

            <div class="control-group">
                <label for="Description" class="control-label">Description</label>
                <div class="controls">
                    <textarea class="textarea-large ckeditor" id="description-medium" name="Description">{{ data.Description }}</textarea>
                </div>
            </div>

            <div class="form-actions">
                <input type="submit" value="Lưu" name="save" class="btn btn-primary">
                <input type="button" value="Quay lại" onclick=window.location.href="{% url 'demo:index' %}" class="btn btn-danger">
            </div>
        </div>
    </form>
</div>
{% endblock %}

demo/templates/users/index.html
{% extends "base.html" %} {% block content %}

<ul class="clearfix" id="nav-info">
    <li>
        <a href="#">
            <i class="icon-home"></i>
        </a>
    </li>
    <li class="active">
        <a href="#">Quản lý Users</a>
    </li>
</ul>

<div class="clearfix">

    <h4>
        Danh sách Users
    </h4>

    <div class="row-fluid">
        <div class="span6">
            <div style="float: left">
                <a style="margin: 0; line-height: 30px;" class="btn" href="{% url 'demo:create' %}">Thêm mới</a>
            </div>
        </div>
        <div class="span6">
            <form action="" method="get" enctype="multipart/form-data">
                <div class="dataTables_filter" id="example-datatables_filter">
                    <label>
                        <div class="input-prepend">
                            <span class="add-on">
                                <i class="icon-search"></i>
                            </span>
                            <input type="text" name="s" value="" autocomplete="false" placeholder="Tìm kiếm...">
                        </div>
                    </label>
                </div>
            </form>
        </div>
    </div>


    <table class="table table-bordered" style="margin-top: 10px">
        <thead>
            <tr>
                <th style="width: 10%">
                    STT
                </th>
                <th>
                    FullName
                </th>
                <th>
                    Tùy chọn
                </th>
            </tr>
        </thead>

        <tbody>

            {% if data %} {% for user in data %}
            <tr>
                <td>
                    <div>
                        {{user.id}}
                    </div>
                </td>
                <td>
                    <a href="{% url 'demo:edit' user.id %}">
                        {{user.FullName}}
                    </a>
                </td>
                <td>
                    <a href="{% url 'demo:delete' user.id %}" onclick="return confirm('Bạn có chắc muốn xóa ?');">
                        Xóa
                    </a>
                </td>
            </tr>
            {% endfor %} {% else %}

            <tr>
                <td colspan="3">Chưa có dữ liệu</td>
            </tr>

            {% endif %}

        </tbody>
    </table>

</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Quản Lý</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="{% static "a_files/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "a_files/plugins.css" %}">
    <link rel="stylesheet" href="{% static "a_files/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "a_files/main.css" %}">
    <link rel="stylesheet" href="{% static "a_files/style_support.css" %}">
    <link rel="stylesheet" href="{% static "css/chosen.css" %}">
    <script src="{% static "a_files/jquery-1.9.1.js" %}"></script>

    <script> var rootpath = "<?php echo ROOT; ?>";</script>

    <script src="{% static "js/jquery.chosen.min.js" %}" type="text/javascript"></script>

    <script src="{% static "a_files/jquery-ui.js" %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static "a_files/jquery-ui.css" %}">
    <script src="{% static "a_files/modernizr-2.6.2-respond-1.1.0.min.js" %}" type="text/javascript"></script>
    <script src="{% static "a_files/jquery-1.10.2.min.js" %}" type="text/javascript"></script>
    <script src="{% static "a_files/bootstrap.min.js" %}" type="text/javascript"></script>
    <script src="{% static "a_files/plugins.js" %}" type="text/javascript"></script>
    <script src="{% static "a_files/ckeditor/ckeditor.js" %}" type="text/javascript"></script>
    <script src="{% static "a_files/main.js" %}" type="text/javascript"></script>

    <style>
        .cke {
            visibility: hidden;
        }
    </style>

</head>

<body>

    <script type="text/javascript">
        $(document).ready(function () {
            var sAct = "#Home"
            $(sAct).attr("class", "active");

            $('select.chosen').chosen();
            $('select.chosen-no-search').chosen({ disable_search: true });
        });
    </script>

    <div id="page-container">

        <header class="navbar navbar-inverse">
            {% include "header.html" %}
        </header>

        <div id="inner-container">
            <aside id="page-sidebar" class="nav-collapse collapse">
                <nav id="primary-nav">
                        {% include "sidebar.html" %}
                </nav>
            </aside>
            <div id="page-content" style="min-height: 560px;">
                {% block content %} {% endblock %}
            </div>
            <footer>
                2018 ©
                <strong>Kim Ý Media</strong> - Developed by
                <strong>
                    <a href="#" target="_blank">TMT</a>
                </strong>
            </footer>
        </div>
    </div>
    <a href="#" id="to-top">
        <i class="icon-chevron-up"></i>
    </a>
</body>

</html>

templates/header.html
<div class="navbar-inner remove-radius remove-box-shadow">
    <div class="container-fluid">
        <ul class="nav pull-right visible-phone visible-tablet">
            <li class="divider-vertical remove-margin"></li>
            <li>
                <a href="javascript:void(0)" data-toggle="collapse" data-target=".nav-collapse">
                    <i class="icon-reorder"></i>
                </a>
            </li>
        </ul>

        <a href="#" class="brand">Quản trị viên</a>

        <ul id="widgets" class="nav pull-right">
            <li class="divider-vertical remove-margin"></li>
            <li class="dropdown dropdown-user">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                    Administrator
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#" role="button" data-toggle="modal">
                            <i class="icon-user"></i>Đổi mật khẩu
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <i class="icon-lock"></i>Đăng xuất
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Hello  guys !!!</h1>
{% endblock %}

templates/sidebar.html
<ul>

    <li>
        <a href="#" class="">
            <i class="icon-star"></i>Trang Chủ
        </a>
    </li>

    <li>
        <a id="Statistic" class="active" href="#">
            <i class="icon-folder-open"></i>Users</a>

        <ul style="display:block;">
            <li>
                <a id="Module" href="{% url 'demo:create' %}">Thêm mới</a>
            </li>
            <li>
                <a id="Groups" href="{% url 'demo:index' %}">Xem tất cả Users</a>
            </li>
        </ul>
    </li>
</ul>